### ISSUE TITLE
password is visible in tasklist

### ISSUE THREAD

**Issue by ghost** [ngocvantran/7Pass#1]
Great to have now a mango version. Application switching works great with this version. Someone has the issue to see the clear-text password in the screenshot of the Applist in task switcher. That’s true but i think it’s not a big issue. Every one should use a PIN to start/unlock the phone. So i fit is stolen, you must enter the pin to unlock it.  To add a extra portion of security there could be (optional of course) to relock the database automatically after some time or event/action. Maybe after 5, 10, 15 minutes, relocking the phone, go to standby. Additionally, the password could be hidden with asterisks or dots and only when you press enter the password field, it should be revealed. Than you can copy it in to the paste bin, after this, the password should be automatically hidden by the dots (leave the field, field changed finally or whatever event is possible). I don’t know if this is possible. Personally I don’t need such options but i can understand that this can be useful in some circumstates. Personally i would like to disable these options for faster access.

**Comment by ngocvantran** [comment]
Password box is now displayed as asterisks and until reveals when user taps on it.
Commit: 4475822543b579f035254544bd9715e94cb98782

**Comment by ghost** [comment]
Cool. thanks.
