### ISSUE TITLE
SkyDrive support

### ISSUE THREAD

**Issue by ngocvantran** [ngocvantran/7Pass#2]
Add SkyDrive with full synchronization support.

**Comment by PProvost** [comment]
+1 on this request. Since Windows has now released SkyDrive app for WP7, it should be as simple as letting me load a database from the local documents folder.

SkyDrive for WP7 Official:
http://www.windowsphone.com/en-US/apps/ad543082-80ec-45bb-aa02-ffe7f4182ba8?wa=wsignin1.0

**Comment by ngocvantran** [comment]
Implemented in 3.4 Beta.
